In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')
len(df)

11914

In [7]:
most_pop = df.filter(['Make', 'Popularity']).drop_duplicates().sort_values(by='Make', ascending=True)
makes1 = ['Chevrolet', 'Volkswagen', 'Toyota']
pop_sum1 = most_pop.loc[most_pop['Make'].isin(makes1)].sum()
pop_sum1

Make          ChevroletToyotaVolkswagen
Popularity                         4289
dtype: object

In [8]:
makes2 = ['Chevrolet', 'Ford', 'Toyota']
pop_sum2 = most_pop.loc[most_pop['Make'].isin(makes2)].sum()
pop_sum2

Make          ChevroletFordToyota
Popularity                   9073
dtype: object

In [9]:
makes3 = ['Volkswagen', 'Ford', 'Toyota']
pop_sum3 = most_pop.loc[most_pop['Make'].isin(makes3)].sum()
pop_sum3

Make          FordToyotaVolkswagen
Popularity                    8561
dtype: object

In [10]:
makes4 = ['Chevrolet', 'Ford', 'Volkswagen']
pop_sum4 = most_pop.loc[most_pop['Make'].isin(makes4)].sum()
pop_sum4

Make          ChevroletFordVolkswagen
Popularity                       7915
dtype: object

In [11]:
audis = df.loc[df['Make'] == 'Audi'].filter(['Make', 'Model']).drop_duplicates()
audis.count()

Make     34
Model    34
dtype: int64

In [12]:
df.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [13]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [14]:
df['Engine Cylinders'].median()

6.0

In [15]:
df['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [16]:
df['Engine Cylinders'].fillna(4.0)

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [17]:
df['Engine Cylinders'].median()

6.0

In [23]:
lotus = df.loc[df['Make'] == 'Lotus'].filter(['Engine HP', 'Engine Cylinders'])
lotus.head()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [25]:
lotus.drop_duplicates(inplace=True)
lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [37]:
X = lotus.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [38]:
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [45]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [46]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [52]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
prod = XTX_inv.dot(X.T)
prod

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [53]:
w = prod.dot(y)
w

array([  4.59494481, -63.56432501])